- components/Base/Button/Index.vue
- components/Header/index.vue
- Refactor action about with button tertiary
title: Refactor action "about desa digital" with button tertiary
participants: @adzharamrullah @maruf12 @bangunbagustapa @naufalihsank @yoslie @maulanayuseph
> Refactor action "about desa digital" with button tertiary

- components/Base/Button/Index.vue
- components/Header/index.vue
- components/HeroBanner/index.vue
- layouts/default.vue
- nuxt.config.js
- windi.config.js
- Feat: Add title and descriptions on hero banner
title:  Feat: Add title and descriptions on hero banner
participants: @adzharamrullah @Arif9878 @bangunbagustapa @Ibwedagama @maulanayuseph
> Feat: Add title and descriptions on hero banner

- nuxt.config.js
- Change environment target to static
title: Setup environment target to static
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank
> Setup environment target to static

- components/Base/Button/Index.vue
- fix (button) : fix line-height base button for large screen
title: fix (button) : fix line-height base button for large screen
participants: @adzharamrullah @Ibwedagama @bangunbagustapa @yoslie
> fix (button) : fix line-height base button for large screen

- components/Footer/index.vue
- nuxt.config.js
- fix : ios flexbox images on footer
title: fix : ios flexbox images on footer
participants: @abazer27 @adzharamrullah @bangunbagustapa @yoslie @maruf12 @doohanas @naufalihsank
> fix : ios flexbox images on footer

- components/ContactUs/index.vue
- components/Footer/index.vue
- components/Header/index.vue
- components/HeroBanner/index.vue
- components/JoinInfo/index.vue
- nuxt.config.js
- package-lock.json
- package.json
- feat : add feature scrollto for sitemap menu
title: feat : add feature scrollto for sitemap menu
participants: @adzharamrullah @bangunbagustapa @Ibwedagama
> feat : add feature scrollto for sitemap menu

- nuxt.config.js
- package-lock.json
- package.json
- chore: change strategy adding google fonts
title: chore: change strategy adding google fonts
participants: @adzharamrullah @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
> chore: change strategy adding google fonts

- nuxt.config.js
- chore: parseFloat env sentry sample rate
title: chore: parseFloat env sentry sample rate
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank
> chore: parseFloat env sentry sample rate

- components/JoinInfo/index.vue
- fix : padding, margin and text on section join information
title: fix : padding, margin and text on section join information
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
> fix : padding, margin and text

- components/MapsDedi/index.vue
- pages/index.vue
- feat: section maps desa and mitra joined
title: feat: section maps desa and mitra joined
participants: @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
> feat: maps desa and mitra joined

- assets/css/global.postcss
- components/Testimonial/index.vue
- fix: list testimonials
title: fix: list testimonials
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @yoslie
> fix: list testimonials

- components/MapsDedi/MapsDedi.pcss
- fix: background style sidebar content
title: fix: background style sidebar content
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
> fix: background style sidebar content

- components/MapsDedi/MapsDedi.pcss
- components/MapsDedi/index.vue
- components/Testimonial/index.vue
- fix: hidden scroll group chips
title: fix: hidden scroll group chips
participants: @adzharamrullah @maruf12 @Ibwedagama @bangunbagustapa
> fix: hidden scroll group chips

- components/JoinInfo/index.vue
fix: join info dedi image for mini laptop
title: fix: join info dedi image for mini laptop
participants: @adzharamrullah @adzharamrullah @naufalihsank @yoslie @maulanayuseph
> fix: join info dedi image for mini laptop

- windi.config.js
- fix: text and background color level villages
title: fix: text and background color level villages
participants: @adzharamrullah @maulanayuseph  @Ibwedagama @bangunbagustapa
> fix: text and background color level villages

- components/MapsDedi/index.vue
- mixins/InfoWindows.js
- windi.config.js
- fix: style image rounded villages
title: fix: style image rounded villages
participants: @adzharamrullah @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
> fix: style image rounded villages

- mixins/MapsDedi.js
- fix: bugs on filter and search sidebar list villages
title: fix: bugs on filter and search sidebar list villages
participants: @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @yoslie
> fix: bugs on filter and search sidebar list villages

- components/MapsDedi/MapsDedi.pcss
- mixins/InfoWindows.js
- fix: style level on mobile screen
title: fix: style level on mobile screen
participants: @adzharamrullah @maulanayuseph @maruf12 @Ibwedagama @bangunbagustapa @yoslie
> fix: style level on mobile screen

- mixins/InfoWindows.js
- fix: styling popup info window images desa digital
title: fix: styling popup info window images desa digital
participants: @adzharamrullah @Ibwedagama @bangunbagustapa @maruf12
> fix: styling popup info window images desa digital

- components/Testimonial/index.vue
- fix: remove manipulations avatar images list testimonials
title: fix: remove manipulations avatar images list testimonials
participants: @adzharamrullah @Ibwedagama @bangunbagustapa @naufalihsank
> fix: remove manipulations avatar images list testimonials

- components/HeroBanner/index.vue
- components/JoinInfo/index.vue
- components/VillagePartner/index.vue
- Updates content 
- Add margin-bottom in village partner section
- Change line-height in the join info section
- Change font size and line height in hero banner section
title: Refactor: updates content and change styling
participants:  @adzharamrullah @Ibwedagama @maulanayuseph @maruf12 @yoslie
> refactor: updates content and change styling

- components/JoinDedi/index.vue
- feat: improve animation transition CTA join desa digital
title: feat: improve animation transition CTA join desa digital
participants: @adzharamrullah @Ibwedagama @bangunbagustapa
> feat: improve animation transition CTA join desa digital

- mixins/InfoWindows.js
- fix: handle undefined or empty text in info window
title: fix: handle undefined or empty text in info window
participants: @adzharamrullah @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
> fix: handle undefined or empty text in info window

- docs/pull_request_template.md
- fix: change participants
title: fix: change participants
participants: @adzharamrullah
> fix: change participants

- components/AboutDedi/index.vue
- components/MapsDedi/MapsDedi.pcss
- components/MapsDedi/index.vue
- feat: section modal about dedi
title: feat: section modal about dedi
participants: @adzharamrullah
> feat: section modal about dedi

- components/Registration/Mitra/index.vue
1. https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/reczqnUdNXMHSZfRL?blocks=hide
2. https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recnWcxuwY3iuVwWL?blocks=hide
- Feature to submit form registration for sign up
- Notification when user success submit
1. feature to submit form registration for sign up and notification success
title: feat(success-registration): success submit the registration form to sign up
participants: @doohanas @adzharamrullah @yoslie @bangunbagustapa @Ibwedagama @maulanayuseph
> feat(success-registration): success submit the registration form for sign up

- components/Registration/Mitra/index.vue
1. https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/rec7I9V6Eg0e97jmD?blocks=hide
1. Button disabled while the password level is `Tidak cukup kuat`
2. Show alert while `kata sandi` and `ulangi kata sandi` isn't the same
1. Button disabled while the password level is `Tidak cukup kuat`
2. Show alert while `kata sandi` and `ulangi kata sandi` isn't the same
title: feat/failed registration: condition failed to create account
participants: @doohanas @adzharamrullah @maulanayuseph @Ibwedagama @bangunbagustapa @naufalihsank
> feat/failed registration: condition failed to create account

- components/Base/input/Input.pcss
- components/Base/input/index.vue
- components/Registration/Mitra/index.vue
1. Add validation and error message for email input
1. Add validation and error message for email input
title: feat/input component: add validation and error message for email input
participants: @doohanas @yoslie @bangunbagustapa @Ibwedagama @maulanayuseph @adzharamrullah
> feat/input component: add validation and error message for email input

- components/Registration/Mitra/index.vue
As described in title.
Before:
After:
https://user-images.githubusercontent.com/65396086/161677530-a9a79bc2-bbea-427a-8a17-b32f1b68ab87.mov
title: Fix layout responsive tablet size page registrasi mitra
participants: @yoslie @adzharamrullah @maulanayuseph @bangunbagustapa @doohanas
> fix: responsive tablet page registrasi mitra

- components/Footer/index.vue
- components/Testimonial/index.vue
1. The 'Testimoni User' in the footer will scroll up to the 'Testimonial' section
1. The 'Testimoni User' in the footer will scroll up to the 'Testimonial' section
title: fix(footer-scroll-up): 'Testimoni User' hyperlink
participants: @doohanas @adzharamrullah @yoslie @maulanayuseph
> fix(footer-scroll-up): 'Testimoni User' hyperlink

- components/Questionnaire/One/index.vue
- update endpoints file uploads
- create temporary id for testing
title: update endpoints files upload
participants: @yoslie @maulanayuseph @Ibwedagama @doohanas
> refactor: update endpoints files upload

- components/Base/Toast/Toast.pcss
- components/Base/Toast/index.vue
- components/Questionnaire/One/index.vue
- pages/registration.vue
- store/toast.js
- add component base toast
- apply toast in error handling on submit questionnaire level one
- remove unused code in questionnaire one
Preview:
title: Add Component Base Toast & Refactor code Questionnaire one
participants: @yoslie @ihsannaufalk @maruf_harsono @maulanayuseph @Ibwedagama @doohanas
> feat: Add Component Base Toast

- components/Questionnaire/Three/index.vue
- constants/questionnaire.js
note: deploy preview unavailable, here is the overview page:
https://user-images.githubusercontent.com/65396086/163757011-d756b0d5-afb3-40a8-9f0e-f05964e559a7.mov
title: Slicing layout questionnaire level three
participants: @yoslie @Ibwedagama @doohanas @maulanayuseph
> feat: slicing layout questionnaire level three

- components/Questionnaire/Questionnaire.pcss
- components/Questionnaire/Two/index.vue
- constants/questionnaire.js
https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recVGJtKOtjDyuop8?blocks=hide
1. slicing layout questionnaire level two
1. slicing layout questionnaire level two
title: feat(questionnaire-2): slicing layout questionnaire level two
participants: @doohanas @Ibwedagama @yoslie
> feat(questionnaire-2): slicing layout questionnaire level two

- components/Questionnaire/Two/index.vue
1. Add function to upload image in form section and show notification modal level two
1.  Add function to upload image in form section and show notification modal level two
title: feat(questionnaire-two-function): to upload image in form section and show notification modal level two
participants: @doohanas @adzharamrullah @yoslie @naufalihsank
> feat(questionnaire-two-function): to upload image in form section and show notification modal level two

- components/Questionnaire/Three/index.vue
- constants/questionnaire.js
- Add questionnaire level 4
- Update functional form
- Minor wording `Bapak dan Ibu` into `Bapak/Ibu`
title: update questionnaire level three and add questionnaire level 4
participants: @yoslie @Ibwedagama @doohanas @maulanayuseph
> feat: update questionnaire level three and add questionnaire level 4

- components/JoinDedi/index.vue
- pages/registration.vue
- store/index.js
Fix state not saved / cached if refresh page, so we change the way we route it.
Before:
https://user-images.githubusercontent.com/65396086/165012826-5059d0f0-7fcf-46bb-b84c-ab235fc0bc80.mov
After:
https://user-images.githubusercontent.com/65396086/165012888-8a44c7e2-8856-447b-94bc-e2f733698144.mov
title: ix route from options Join Dedi
participants: @yoslie @ihsannaufalk @maulanayuseph @bangunbagustapa @doohanas @agunghide
> fix: Fix route from options Join Dedi

- components/Questionnaire/Three/index.vue
- components/Questionnaire/index.vue
1. Create validation questionnaire level three
2. Refactor the layout of the `questionnaire-three` component
1. Create validation questionnaire level three
title: feat(validation-questionnaire-three): Create validation questionnaire level three
participants: @doohanas @yoslie @agunghide @maulanayuseph @naufalihsank
> feat(validation-questionnaire-three): Create validation questionnaire level three

- components/Questionnaire/One/index.vue
- components/Questionnaire/Two/index.vue
- components/Questionnaire/index.vue
- constants/questionnaire.js
- Change the input form type checkbox in questionnaire level one and two
- Add a new feat to show and hide input images and data when the user chooses a value in input type radio or checkbox
1.  Questionnaire level one
- Change the input form type checkbox
-  Add a new feat to show and hide input images and data when the user chooses a value in input type radio or checkbox
2.  Questionnaire level two
- Change the input form type checkbox
- Add a new feat to show and hide input images and data when the user chooses a value in input type radio or checkbox
title: refactor: update form in questionnaire levels one and two
participants: @doohanas @yoslie
> refactor: update form in questionnaire level one and two

- components/Modal/Notification/index.vue
- constants/questionnaire.js
- Add `level` props to define a content
- Update content in questionnaire-notification
1. Update content in questionnaire-notification
title: feat: update questionnaire notification component
participants: @doohanas @Ibwedagama @agunghide @yoslie @maulanayuseph
> feat: update questionnaire notification component

- components/Questionnaire/index.vue
- Update validation questionnaire two to show a notification after submitting the form
1. Update validation questionnaire two to show a notification after submitting the form
title: feat (validation-questionnaire-two): update to show notification after submit
participants: @doohanas @yoslie @Ibwedagama @agunghide @bangunbagustapa @maulanayuseph
> feat (validation-questionnaire-two): update to show notification after submit

- components/Base/Dialog/Dialog.pcss
- components/Base/Dialog/index.vue
- pages/registration.vue
- store/dialog.js
as described in title
title: Add component Base Dialog
participants: @yoslie @doohanas @bangunbagustapa @agunghide
> feat: Add component Base Dialog

- components/Questionnaire/Three/index.vue
- components/Questionnaire/index.vue
- Update validation questionnaire three to show a notification page after submitting the form
- Change properties `bumdes` dan `potensi` value from empty string to null
1. Update validation questionnaire three to show a notification page after submitting the form
title: feat: update validation questionnaire three
participants: @doohanas @yoslie @maulanayuseph @bangunbagustapa @agunghide
> feat: update validation questionnaire three

- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/Questionnaire.pcss
- components/Questionnaire/index.vue
as described in title
title: Apply functionality in form confirmation questionnaire
participants: @yoslie @doohanas @agunghide
> feat: apply functionality in form confirmation questionnaire

- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/Questionnaire.pcss
Create village (Desa/Kelurahan) validation for Questionnaire
title: Create village (Desa/Kelurahan) validation for Questionnaire
participants: @yoslie @doohanas @bangunbagustapa @maulanayuseph @agunghide
> feat: Create Questionnaire Village validation function

- components/Questionnaire/Notification/index.vue
- components/Questionnaire/index.vue
- nuxt.config.js
- Add the show and hide method on the `potency button` in questionnaire-notification when questionnaire level four is `true`
- Add function to open link in a new tab but the link must update in next pr
title: feat: update validation questionnaire four
participants: @doohanas @bangunbagustapa @yoslie @agunghide
> feat: update validation questionnaire four

- components/Partner/index.vue
- Change pathname in the source image
title: refactor (mitra): change pathname in the source image
participants: @doohanas @maruf12 @yoslie @agunghide @maulanayuseph
> refactor (mitra): change pathname  in the source image

- components/Base/input/Input.pcss
- components/Base/input/index.vue
- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/index.vue
- update error validation in questionnaire confirmation page
- update style base input color
- update id village (replace default hardcode id village with actual id village)
title: Update form validation in Questionnaire confirmation
participants: @yoslie @ihsannaufalk @maulanayuseph @bangunbagustapa @doohanas @agunghide
> feat: update form validation in Questionnaire confirmation

- components/Questionnaire/One/index.vue
- Update questionnaire one: add a new feature to check all options in the questionnaire one is filled, except `textarea` and `upload photo/file`
1. add a new feature to check all options in the questionnaire one is filled
title: feat (validation-questionnaire-one): to check all options in the questionnaire one is filled
participants: @doohanas @yoslie @naufalihsank @bangunbagustapa
> feat (validation-questionnaire-one): to check all options in the questionnaire one is filled

- components/Questionnaire/Three/index.vue
as described in title
title: Update form validation on questionnaire three and questionnaire four
participants: @yoslie @agunghide @doohanas @maulanayuseph
> feat: update form validation on questionnaire three and questionnaire four

- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/One/index.vue
- components/Questionnaire/Questionnaire.pcss
- components/Questionnaire/index.vue
- constants/questionnaire.js
- Fix style (height and width) and class name attributes in the questionnaire
- Fix typo content in questionnaire notification
1. Fix style (height and width) and class name attributes in the questionnaire
- Before 
- After
title: refactor (registration village): fix astyle village registration form 
participants: @doohanas @yoslie @Ibwedagama @bangunbagustapa
> refactor (registration village): fix style village registration form 

- components/Header/index.vue
- pages/competition.vue
- Create a new page for `sayembara`
- Add a new button in header to redirect to `sayembara` page
1. Add a new button in header to redirect to `sayembara` page
title: feat(sayembara-structure): create a new page (sayembara)
participants: @doohanas @yoslie @bangunbagustapa
> feat(sayembara-structure): create a new page (sayembara)

- components/MapsDedi/index.vue
- mixins/MapsDedi.js
- add `is_active` params in `maps-dedi` to activate maps feature
title: chore (maps-dedi): add new params to activate the maps feature
participants: @doohanas @bangunbagustapa @yoslie @agunghide
> chore (maps-dedi): add new params to activate maps feature

- .github/workflows/production.yml
- chore: add config github workflows production
title: chore: add config github workflows production
participants: @adzharamrullah  @doohanas
> chore: add config github workflows production

- .github/workflows/production.yml
- SetUp ArgoCD auto MR deploy production
title: SetUp ArgoCD auto MR deploy production
participants: @ayocodingit @feriahmad  @adzharamrullah
> SetUp ArgoCD auto MR deploy production

- components/AboutBanner/index.vue
- components/Competition/About/index.vue
- components/Competition/Banner/index.vue
- components/Footer/index.vue
- components/TheySaid/index.vue
- constants/footer.js
1. [Footer ](https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recStqdwm5MRqYGjZ?blocks=hide )Section 
- Create a footer section in competition-page
- Fix the footer section in about-page
1. Create a footer section in competition-page
2. Fix the footer section in about-page
- Before
- After
title: feat (footer): create a new footer section on competition-page and fix the footer in about-page 
participants: @doohanas @yoslie @agunghide
> feat (footer): create a new footer section on competition-page and fix the footer in about-page

- components/Competition/Flow/Detail/index.vue
- Update content section info to fix jds-icon not shown
- Update minor missing dot (.) in wording info
title: Fix Section info detail flow competition
participants: @yoslie @maulanayuseph @Ibwedagama @doohanas @agunghide
> fix: Fix Section info detail flow competition

- components/DevelopmentStage/index.vue
- constants/footer.js
Fix link in footer sites section not worked for three pillars and development stage
title: Fix link in footer sites section not worked for three pillars and development stage
participants: @yoslie @ihsannaufalk @maulanayuseph @Ibwedagama @doohanas @agunghide
> fix: fix some link sites not worked in footer section

- components/Card/Achievement/index.vue
- components/HeroBanner/index.vue
- Update motif hero banner to stick when swiped
- Hide pagination bullets when only 1 banner
title: Update style hero banner landing page
participants: @yoslie @ihsannaufalk @Ibwedagama @doohanas
> style: Update style hero banner landing page

- assets/css/global.postcss
- components/Base/input/index.vue
- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/One/index.vue
- components/Questionnaire/Three/index.vue
- components/Questionnaire/Two/index.vue
Update required style in questionnaire: confirmation, level one, level two, level three, and level four
title: Update required style in questionnaire: confirmation, level one, level two, level three, and level four
participants: @yoslie @Ibwedagama
> style: add required style in questionnaire form

- components/Questionnaire/Confirmation/index.vue
- components/Registration/Mitra/index.vue
1. [Hide ](https://airtable.com/appdN4AdnU8FNs94M/tblH4guPTd65ntqNq/viwWvQmeD8YN2sEgY/rec2EJFowoGEYPORg?blocks=hide)`Masuk Disini` Feature on Registration Mitra
- Add `v-show` attribute to hide the `Masuk Disini` Feature in `registration-mitra`
1. Hide button login in `registration-mitra`
- Beforre
- After
title: refactor (registration-mitra): add the v-show attribute to hide the masuk-disini feature
participants: @doohanas @Ibwedagama @yoslie @naufalihsank
> refactor (registration-mitra): add v-show attribute to hide the masuk-disini feature

- components/Footer/index.vue
1. [Update](https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recuifDmjyaiM6qSR?blocks=hide) social media links in footer
- Add JDS social media links in `href` attribute
- Add `blank` as the value of `target` attribute to open a new window
- Replace the name of the social media in `alt` attribute
1. Facebook
https://user-images.githubusercontent.com/79241754/172527202-32c66601-e1da-44f0-a8cc-555e12330e49.mp4
2. Youtube
https://user-images.githubusercontent.com/79241754/172527449-4a09b12e-be39-488e-830f-6485dfaf3c45.mp4
3. Instagram
https://user-images.githubusercontent.com/79241754/172527279-f823feaf-f72f-4f38-96c4-c031077b295a.mp4
4. Twitter
https://user-images.githubusercontent.com/79241754/172527296-795ffa9c-5f51-4ef2-8edc-bea05a4e8fd2.mp4
title: refactor …
> refactor (footer): add JDS social media links

- components/HeroBanner/index.vue
- Fix onclick hero banner landing page not worked
- Minor update ref naming swiper hero banner
title: Fix onclick hero banner landing page not worked
participants: @yoslie @doohanas @maruf_harsono @agunghide
> fix: hero banner click function

- components/Questionnaire/Notification/index.vue
- Update date in content `notification` modal
- Add style in `atau` word
1. Update date and add style in `atau` word
title: refactor (questionnaire): update date of content and add style in 'atau' word
participants: @doohanas @maulanayuseph @agunghide @yoslie
> refactor (questionnaire): update date in content notification and add style in 'atau' word

- components/Questionnaire/Confirmation/index.vue
Add simple phone number validation
Task: [T36 - Landing Page - Kuesioner - Tambah validasi no hp max 13 angka](https://airtable.com/appdN4AdnU8FNs94M/tblH4guPTd65ntqNq/viwWvQmeD8YN2sEgY/recQsgFTU8lhLYHbj?blocks=hide)
title: Add simple phone number validation
participants: @yoslie @ihsannaufalk @maulanayuseph @doohanas
> feat: add simple phone number validation

- components/DevelopmentStage/index.vue
- components/Modal/InfoVillage/index.vue
- Add `thematics` data in the `development-stage` and `modal-infoVillage` component
- Show `thematics` data using `Transition-group`
1. Thematics in the `development-stage` component 
2. Thematics in the `modal-infoVillage` component 
3. Transition in `Desa Digital 4.0`
https://user-images.githubusercontent.com/79241754/172975802-c68af66a-8388-46da-8152-3a20621ddf74.mp4
1. Improvement is needed to make reusable components for two of the `development-stage` and the `modal-infoVillage` component.
title: refactor (development-stage): add new content in development stage
participants: @doohanas @Ibwedagama @agunghide
> refactor (development-stage): add new content in development stage

- components/Card/Testimonials/index.vue
- components/HeroBanner/index.vue
Before:
After:
title: fix style hero-banner
participants: @yoslie
> style: fix style hero-banner

- nuxt.config.js
- package-lock.json
- package.json
- plugins/gtag.js
- feat: Setup Google Analytics 4
Environment GA4 Should Change @doohanas @yoslie 
title: feat: Setup Google Analytics 4
participants: @adzharamrullah @doohanas @yoslie
> feat: Setup Google Analytics 4

- components/HeroBanner/index.vue
- components/Testimonial/index.vue
- Add the `is_active` variable query in the testimonial and set the value is `true` to show the content
- Add `is_active`, `order_by`, and `sort_by` variables query in the `HeroBannerand`  set the value is `true` to show the content
title: chore (index-page): add query variable in testimonial and hero banner section
participants: @doohanas @Ibwedagama @agunghide
> chore (index-page): add a new variable query in testimonial and hero banner section

- components/Partner/index.vue
replace mitra field created at with join year
title: Replace mitra field created at with join year
participants: @yoslie @doohanas @Ibwedagama
> fix: replace mitra field created at with join year

- .github/workflows/production.yml
- .github/workflows/staging.yml
- hotfix: github workflow secret env redirect uri
title: hotfix: github workflow secret env redirect uri
participants: @adzharamrullah @doohanas @yoslie
> hotfix: github workflow secret env redirect uri

- .github/workflows/production.yml
- .github/workflows/staging.yml
- nuxt.config.js
- hotfix: sentry environment workflow
title: hotfix: sentry environment workflow
participants: @adzharamrullah @doohanas @yoslie
> hotfix: sentry environment workflow

- components/JoinDedi/index.vue
1. [Technical-Debt] - [Add](https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recIdDOZU1XAQrTIv?blocks=hide) detail informasi pendaftaran pada modal awal kuesioner
- Add info message to disclaimer user in `join-dedi-modal`
- Add modifier to `overflow` content on mobile screen
1. Add info message to disclaimer user in `join-dedi-modal`
2. Add modifier to `overflow` content on mobile screen
https://user-images.githubusercontent.com/79241754/173989949-a94e2c83-2beb-4aaf-b17e-4884d25372ba.mp4
title: feat (join-dedi-modal): add info message to disclaimer user
participants: @doohanas @adzharamrullah @yoslie @agunghide @naufalihsank
> feat (join-dedi-modal): add info message to disclaimer user

- components/Competition/Criteria/Mitra/index.vue
- components/Header/index.vue
- pages/sayembara.vue
- Fix the typo and change the competition page to sayembara
- Before
- After
title: hotfix (competition): fix typo and change the competition page to sayembara
participants: @doohanas @yoslie
> hotfix (competition): fix typo and change the competition page to sayembara

- components/Sidebar/Mobile/index.vue
- Change routing name from competition to sayembara
title: refactor (sidebar): change routing name from competition to sayembara
participants: @doohanas @yoslie @agunghide @maulanayuseph
> refactor (sidebar): change routing name from competition to sayembara

- components/Potency/index.vue
Update content text and adjust style in page About Desa digital section Potency
title: Update content text and adjust style in page About Desa digital section Potency
participants: @yoslie @agunghide @Ibwedagama @doohanas @maruf_harsono
> style: Update content text and adjust style in page About Desa digital section Potency

- components/AboutDedi/index.vue
1. [About](https://airtable.com/appdN4AdnU8FNs94M/tblH4guPTd65ntqNq/viwWvQmeD8YN2sEgY/recpnNtXoQUeoMbzt?blocks=hide) dedi content in level 4
- refactor (about-dedi): add thematics content for desa-digital lv 4
1. add thematics content for desa-digital lv 4
- Before
- After
title: refactor (about-dedi): add thematics content for desa-digital lv 4
participants: @doohanas @agunghide @yoslie
> refactor (about-dedi): add thematics content for desa-digital lv 4

- components/Partner/Partner.pcss
- components/Partner/index.vue
- update image mitra size
- update font color
- update font size
title: Update content image and font style content list mitra
participants: @yoslie @doohanas @Ibwedagama @agunghide
> style: update style content list mitra

- components/TheySaid/index.vue
- fix capitalize of image source in `they-said` component
title: refactor (they-said): fix capitalize of image source
participants: @doohanas @Ibwedagama @adzharamrullah @agunghide
> refactor (they-said): fix capitalize of image source

- components/Footer/index.vue
- constants/footer.js
1. Update [Footer](https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwlpGjUkaHCytKMk/recRuREMLyFYaOzRE?blocks=hide)
- Change telephone number 
- Change `testimoni user` text to `testimonial` in sitemap
1. Change telephone number and  `testimoni user` text to `testimonial` in sitemap
- Before
- After
title: update (footer): change telephone number and text in sitemap
participants: @doohanas @yoslie @naufalihsank @agunghide
> update (footer): change telephone number and text in sitemap

- assets/css/global.postcss
- components/Questionnaire/Questionnaire.pcss
update scrollbar style in Questionnaire
title: update scrollbar style in Questionnaire
participants: @yoslie @ihsannaufalk @doohanas @agunghide @maruf_harsono
> style: update scrollbar style in Questionnaire

- components/Card/Pillars/index.vue
- components/ThreePillars/index.vue
update content text about dedi section pillars
title: Update content text about dedi section pillars
participants: @yoslie @doohanas @agunghide @maulanayuseph
> refactor: update content text about dedi section pillars

- components/JoinInfo/index.vue
replace wrapper with manual padding in section join info landing page
title: Replace wrapper with manual padding in section join info landing page
participants: @yoslie @doohanas @maulanayuseph @agunghide @Ibwedagama
> style: replace wrapper with manual padding in section join info landing page

- components/Competition/VillageCriteria/index.vue
add wrapper class inside village criteria
title: Add wrapper class inside village criteria section
participants: @yoslie @agunghide @Ibwedagama @doohanas
> style: add wrapper class inside village criteria section

- components/VillagePartner/index.vue
- Improvement showing data in `village-partner` component to change static data into dynamic data
1. Improvement showing data in `village-partner` component to change static data into dynamic data
- Before
- After
title: feat (village-partner): improvement change static data to dynamic data
participants: @doohanas @agunghide @Ibwedagama @yoslie
> feat (village-partner): improvement change static data to dynamic data

- assets/css/global.postcss
- components/JoinInfo/index.vue
- update style scrollbar horizontal
- update style for specific html page
title: Update horizontal join info scrollbar and page scrollbar style
participants: @yoslie @Ibwedagama @agunghide @doohanas
> style: update style scrollbar

- components/Questionnaire/Notification/index.vue
- Change the date of the content in the `questionnaire-notification` component
- Change the link in efishery and agriculture form
1. Change the date of the content and link in efishery and agriculture form
- Before
- After
1. Link for efishery and agriculture form was updated in caprover
title: refactor (questionnaire-notification): change the date of the content and link in efishery and agriculture form
participants: @doohanas @yoslie @maulanayuseph @maruf12 @agunghide
> refactor (questionnaire-notification): change the date of the content and link in efishery and agriculture form

- components/Competition/About/index.vue
- Change microcopy in competition-about section
1. Change microcopy in competition-about section
- Before
- After
title: refactor (competition-about): change microcopy in competition-about section
participants: @doohanas @Ibwedagama @maulanayuseph @agunghide
> refactor (competition-about): change microcopy in competition-about section

- components/Partner/index.vue
- components/VillagePartner/index.vue
1. [Fixing](https://airtable.com/appdN4AdnU8FNs94M/tblH4guPTd65ntqNq/viwWvQmeD8YN2sEgY/reclv0Pl9ci17wFNm?blocks=hide) logic business when register partner
- Add new params in village partner to verification Mitra before the Mitra shows on landing page
title: hotfix (village-partner): add new params in village partner to verification Mitra
participants: @doohanas @yoslie @agunghide
> hotfix (village-partner): add new params in village partner to verification Mitra

- components/JoinDedi/index.vue
update style img and responsive popup join dedi
title: Update style img and responsive popup join dedi
participants: @yoslie @maruf_harsono @doohanas @Ibwedagama @agunghide
> style: update style img and responsive popup join dedi

- components/Partner/Partner.pcss
update typography style mitra list
title: Update typography style mitra list
participants: @yoslie @doohanas @agunghide @Ibwedagama @maulanayuseph
> style: update typography style mitra list

- components/Competition/VillageCriteria/index.vue
- update style responsive
- update height in specific content
title: Update responsive style and fix height for specific content in section Village Criteria
participants: @yoslie @doohanas @agunghide @Ibwedagama @maulanayuseph
> style: update style village criteria

- components/Questionnaire/Confirmation/index.vue
- components/Questionnaire/One/index.vue
- components/Questionnaire/Questionnaire.pcss
- components/Questionnaire/Three/index.vue
- components/Questionnaire/Two/index.vue
1. [Add](https://airtable.com/appdN4AdnU8FNs94M/tblH4guPTd65ntqNq/viwWvQmeD8YN2sEgY/recS9O8UVHVW2lx22?blocks=hide) special characters validation
- Add trim modifier in `text` and `textarea` input
- Add special characters validation for `text` and `textarea` input in `questionnaire` component
1. Add special characters validation for `text` input 
https://user-images.githubusercontent.com/79241754/176225642-1c883f1d-459c-4130-812d-715423dfebf1.mp4
2. Add special characters validation for `textarea` in `questionnaire` component
- The `border-color` when error and hover in `jds-text-area` isn't not shown. So, needs improvement to create BaseTextarea or debug `jds-text-area`. 
title: improvement (questionnaire): add trim modifier and special characters validation for textarea
project: Desa …
> improvement (questionnaire): add trim modifier and special characters validation for textarea

- components/Achievement/index.vue
- components/DevelopmentStage/index.vue
- components/Potency/index.vue
- components/Team/index.vue
- components/TheySaid/index.vue
- components/ThreePillars/index.vue
update responsive padding between section in page about
title: Update responsive padding each section in page about
participants: @yoslie @Ibwedagama @maruf_harsono @doohanas @agunghide @maulanayuseph
> style: update responsive padding each section in page about

- components/Competition/Flow/index.vue
- fix margin content image to button
- fix wrapper section max width
title: Fix margin image to button & fix wrapper max width in section competition flow
participants: @yoslie @Ibwedagama @agunghide @maulanayuseph @doohanas
> style: update style competition flow

- components/MapsDedi/index.vue
1. Hide information total info-village in 'Pencarian Desa'
- Add v-show to hide and show the amount of total village
1. Add v-show to hide and show the amount of total village
https://user-images.githubusercontent.com/79241754/176847309-0b0c0937-5b12-4699-b7fc-01129b70f7f6.mp4
title: feat (search-village): add v-show to hide and show the amount of total village
participants: @doohanas @maruf12 @agunghide @Ibwedagama @yoslie
> feat (search-village): add v-show to hide and show the amount of total village

- Dockerfile
- fix (dockerfile): change name node
title: fix (dockerfile): change name node
participants: @doohanas @ayocodingit @yoslie
> fix (dockerfile): change name node

- components/AboutBanner/index.vue
- change wrapper class
- change responsive content text
Before:
After:
title: Fix wrapper and content text style hero banner page about
participants: @yoslie @doohanas @agunghide @maulanayuseph @Ibwedagama
> style: fix wrapper and content text style hero banner page about

- components/Card/Pillars/index.vue
- components/ThreePillars/index.vue
refactor and fix responsive width card pillars in page about
Before:
https://user-images.githubusercontent.com/65396086/177113198-77acb603-5bf7-4d90-8a1c-abc6b8392d60.mov
After:
https://user-images.githubusercontent.com/65396086/177113590-7eb9e523-b0c5-4e06-a2d5-807e74501ddb.m@ov
title: Refactor and fix responsive width card pillars in page about
participants: @yoslie @Ibwedagama @agunghide @@ihsannaufalk
> style: refactor and fix responsive width card pillars in page about

- components/Questionnaire/Notification/index.vue
- refactor (questionnaire-notification): change the date in the questionnaire
title: refactor (questionnaire-notification): change the date in the questionnaire
participants: @doohanas @ayocodingit @yoslie @Ibwedagama
> refactor (questionnaire-notification): change the date in the questionnaire

- .github/workflows/production.yml
- change on relaase to on push workflows production
title: change on relaase to on push workflows production
participants: @ayocodingit @yoslie @doohanas
> change on relaase to on push workflows production

- components/AboutBanner/index.vue
- components/Competition/Banner/index.vue
- components/Competition/Join/index.vue
- pages/about.vue
- pages/sayembara.vue
- improvement (join-dedi): change label name button join-dedi and create method open questionnaire page 
- Change label name button join-dedi and create method open questionnaire page 
https://user-images.githubusercontent.com/79241754/178637043-bac21df5-bc16-4d43-84f8-05ee99b56585.mp4
title: improvement (join-dedi): change label name button join-dedi and create method open questionnaire page
participants: @doohanas @yoslie @agunghide
> improvement (join-dedi): change label name button join-dedi and create method open questionnaire page

- components/Competition/Banner/index.vue
- pages/sayembara.vue
change behavior on click cta in hero banner page sayembara to directly open pdf link
title: change behavior on click cta in hero banner page sayembara
participants: @yoslie @doohanas @Ibwedagama @agunghide
> refactor: change behavior on click cta in hero banner page sayembara

- components/Achievement/index.vue
- components/Card/Achievement/index.vue
as described in title
title: Bug fix shadow cropped by adjust margin swiper on achievement cards page about
participants: @yoslie @Ibwedagama @maruf12 @maulanayuseph @agunghide @doohanas
> style: fix shadow cropped by adjust margin swiper

- components/ContactUs/index.vue
[Change link hotline Desa Digital](https://app.clickup.com/t/860pdw29h)
- Change the link in the `contact-us` component
title: improvement (contact-us): change link for the contact person
participants: @doohanas @maruf12 @yoslie
> improvement (contact-us): change link for the contact person

- components/ContactUs/index.vue
- hotfix: change hotline link in contact us section
title: hotfix: change hotline link in the contact us section
participants: @doohanas @yoslie
> hotfix: change hotline link in the contact us section

- components/ContactUs/index.vue
- refactor: update the link for the hotline in `contact us` component
title: refactor (contact-us): update link for hotline
participants: @doohanas @Ibwedagama @naufalihsank
> refactor (contact-us): update link for hotline

- components/Competition/Flow/Detail/index.vue
update data in competition flow detail
title: update data in competition flow detail
participants: @yoslie @Ibwedagama @agunghide
> improvement: update data in competition flow detail

- components/ContactUs/index.vue
update contact hotline desa digital
title: update contact hotline desa digital
participants: @yoslie
> hotfix: update contact hotline desa digital

- components/AboutBanner/index.vue
bugfix display hero banner in about page
title: bugfix display hero banner in about page
participants: @yoslie
> hotfix: bugfix display hero banner in about page
